### ISSUE TITLE
Update Reset World

### ISSUE THREAD

**Issue by TheGreatNaj** [IHOC/Server#10]
Forgive me for not following the format but it's not a crash and most of the info is probably irrelevant. I've been enjoying the custom Sky Factory pack recently and made a lot of progress. I hadn't played it for a couple days and when I opened it up today it asked if I wanted to download the update (2.0), so I did. Finally loads up and I join my single player world, everything was gone. Im standing on the starting tree again but I still have my armor and anything that was in my hotbar. I was thinking if I could revert back to 1.2 I might be able to salvage a back up but I can't find any way to revert back.
Is there any way I could possibly get my save back or do I need to accept my loss?

**Comment by Gunner76th** [comment]
If you are playing on a previous save, do /spawn and it should take you to your tree. In ssp spawn is where your island is when you start the game, since you used a previously saved game, it created a new island 1500 meters from your first island. 

Also, because we do not use the solder system, reverting to previous versions is not possible.

**Comment by TheGreatNaj** [comment]
Ugh, yes its there lol Thank you so much! Sorry if it says this info somewhere already and I just missed it, I wouldn't doubt I was oblivious enough to do so lol
