### ISSUE TITLE
PROBLEM IN SKYFACTORY INSTALLATION

### ISSUE THREAD

**Issue by Heclysma** [IHOC/Server#5]
When submitting a bug report, to save us and yourself time, and to ensure we actually have the needed information to take care 
of your issue, please make sure you submit the following information (failure to provide all listed information may result in 
your bug not being addressed):

http://gist.github.com is the prefered site for all reports, logs, and lists.

TeamIHOC Server issue occurred on (Identified by modpack installed ie. All The Mods):

Narrative description of issue or crash:
After the download of skyfactory 3, I have some issues about java while the mods are installing. During the 7 phases of installation my java always crash (java(TM) session SE) at the phase 5/7. I'm using java 64bit with 7gb of ram. What can I do to resolve the issue? I can also send screenshot if needed.
Thanks for help and for all the work!

Steps to reproduce the issue or crash: While mods are installed, java crashes every time.

Link to crash report (posted on either http://gist.github.com or http://www.pastebin.com):

Link to console logs (posted on http://gist.github.com):

OS of Client computer:

Version of JAVA on Client:

Version of Minecraft: 1.10.2

Version of Forge:

List of ALL mods installed (posted to either http://www.pastebin.com or http://gist.github.com):

**Comment by Gunner76th** [comment]
Before this issue can be investigated we need more information. In technic goto Launcher Settings, then goto Java Settings. Please write down what version of java is listed in the top, as well as what the memory is set to. 

Also, as stated in the template, we will require a copy of the crash report if you have one, as well as your client-fml-latest.log file. The crash report is found in the folder %path%\Technic\modpacks\sky-factory-3-custom\crash-reports and the console log file is in the folder %path%\Technic\modpacks\sky-factory-3-custom\logs If you need to figure out where your modpack is installed to, open the Launcher Settings, and look at the Install Folder section. 

One last thing we need to know is if you see a file that starts off with hs_pid_err, if this file is present in %path%\Technic\modpacks\sky-factory-3-custom\ your modpack install location must be changed. Please ensure that the Install Folder in the Launcher Options does *NOT* start with c:\users\ If the Install Location does start with C:\users\ then you must change it to a different folder, preferably either c:\technic, or a dedicated drive for video games. This is due to a conflict between Windows and minecraft 1.10.2. 

Once you have supplied the required information (as stated in the template) we can process this issue report, and help find a resolution.

**Comment by Heclysma** [comment]
I am using java 1.8.0_121 64bit with 7GB of memory.
I don't have any crash report because I can't start the game, my issue is during the installation.
![immagine](https://cloud.githubusercontent.com/assets/25374415/22396997/d26f7334-e566-11e6-80e1-ad57ec6cd46c.png)
This is the error I get at the same moment everytime. I don't even started the game once because this is the first installation

**Comment by Heclysma** [comment]
I even changed the install locatione becuase it started with ''C:\users '' but still game doesn't start.

**Comment by Gunner76th** [comment]
As stated previously, we will require your console log files in order to assist with this error. Within the console log we might be able to see what is causing java to fail. Also please look and see if you have ANY files that end in .log in the main install folder. If you have any .log files please provide copies of those as well. As a reminder, you must use http://gist.github.com when submitting your console log file (client-fml-latest.log). 

This particular error however looks to be a problem between windows and your java installation. I would suggest uninstalling ALL installed versions of Java, then go here https://java.com/en/download/manual.jsp and download the "Windows Offline (64-bit)" file. Use that to reinstall Java, and then try to relaunch minecraft.

**Comment by Heclysma** [comment]
At first, thank you very much for all the support you are giving me!
Even if I already had java version you suggested I reinstalled it again just to be sure, and here there is the fml-client-latest.log you told me to require: https://gist.github.com/Heclysma/3767d1ebc4494d518d84dda6b4a259d1
Also in the installation folder of skyfactory, with fml-client-latest I have another types of log (fml-client-1, fml-junk-earlystartup,latest)
It seems that the problem is about waila, beacuse it crashes everytime waila is loading during the process.
I hope this is the right link and the right log beacuse I'm not very expert in this type of thing, If you need more information just ask.

**Comment by Heclysma** [comment]
I tried to play SkyFactory from FTB launcher and I got the exactly same error I have with ATLauncher (java crashes).
What do you think about the crashes? You found out a solution?

**Comment by Gunner76th** [comment]
As this version of our pack is no longer valid, I am closing this issue.
